filter: "evt.Line.Labels.type == 'syslog'"
name: local/domain-admin-parser
description: "Parser pour détecter les logs d'élévation de privilèges domain admin"
debug: true
onsuccess: next_stage
nodes:
  - grok:
      pattern: "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:hostname} %{DATA:program}: %{GREEDYDATA:message}"
      apply_on: Line.Raw
statics:
  - meta: program
    expression: evt.Parsed.program
  - meta: message
    expression: evt.Parsed.message
  - meta: log_type
    value: domain_admin_log