type: trigger
name: local/detect-domain-admin
description: "Détecte les élévations de privilèges domain admin"
filter: evt.Parsed.domain_admin == 'true'
scope:
  type: Hostname
  expression: evt.Meta.machine
labels:
  severity: info
  service: custom
  remediation: false
blackhole: 1m