type: trigger
name: local/detect-domain-admin
description: "Détecte le log 'Est devenu domain Admin'"
filter: "Match('Est devenu domain Admin', evt.Parsed.message) || Match('Est devenu domain Admin', evt.Meta.message)"
scope:
  type: Hostname
  expression: evt.Parsed.hostname
labels:
  severity: info
  service: custom