type: http          # Don't change
name: http_default  # Must match the registered plugin in the profile

# One of "trace", "debug", "info", "warn", "error", "off"
log_level: info

# Ajout de paramètres de groupement pour éviter les notifications dupliquées
group_wait: "5s"         # Attendre 5 secondes pour collecter les alertes
group_threshold: 1       # Envoyer après 1 alerte même si le délai n'est pas écoulé
max_retry: 3             # Nombre de tentatives en cas d'échec
timeout: "10s"           # Délai d'attente avant de considérer une requête comme échouée

#-------------------------
# plugin-specific options

# The following template receives a list of models.Alert objects
# The output goes in the http request body
format: |
  {{.|toJson}}

# The plugin will make requests to this url, eg:  https://www.example.com/
url: https://webhook.site/5fd89e13-e3a0-4716-8d31-6677732e57ab

# Any of the http verbs: "POST", "GET", "PUT"...
method: POST

# headers:
#   Authorization: token 0x64312313

# skip_tls_verification: false  # true or false. Default is false

---

# type: http
# name: http_second_notification
# ...
