filter: "evt.Parsed.message contains 'Domain Admin'"
name: local/domain-admin-s01
description: "Parser pour préserver les logs domain admin en s01-parse"
debug: true
onsuccess: next_stage
statics:
  - parsed: domain_admin
    value: "true"
